[telegram]
token = "token" # Token de autenticación para el bot de Telegram
allowed_ids = [
  1,
  2,
  3,
] # Lista de IDs de usuarios permitidos a interactuar con el bot

[gemini]
token = "token"                # Token de autenticación para la API de Gemini
model = "model"                # Modelo a utilizar para la API de Gemini
google-search-grounding = true # Habilitar el grounding de búsqueda de Google
thinking-level = "low"         # Nivel de pensamiento para la API de Gemini
