[telegram]
token = "token" # Token de autenticación para el bot de Telegram
allowed = [
  1,
  2,
  3,
] # Lista de IDs de usuarios permitidos a interactuar con el bot

[gemini]
token = "token" # Token de autenticación para la API de Gemini
